# Generated by Django 3.2.16 on 2022-10-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=200)),
                ('employee_last_name', models.CharField(max_length=200)),
                ('employee_linkedin_url', models.URLField(blank=True, max_length=500, null=True)),
                ('employee_email_address', models.EmailField(blank=True, max_length=200, null=True)),
                ('employee_title', models.CharField(blank=True, max_length=200, null=True)),
                ('employee_additional_notes', models.TextField(blank=True, null=True)),
                ('employee_created_at', models.DateTimeField(auto_now_add=True)),
                ('employee_updated_at', models.DateTimeField(auto_now=True)),
                ('employee_company_id', models.ManyToManyField(blank=True, to='company.Company')),
            ],
        ),
    ]
