# Generated by Django 3.2.16 on 2022-10-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('compnay_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('company_legal_name', models.CharField(max_length=200)),
                ('company_website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company_corporation_type', models.CharField(blank=True, choices=[('Brand', 'Brand'), ('Retailer', 'Retailer'), ('Other', 'Other')], max_length=200, null=True)),
                ('company_date_of_incorporation', models.DateField(blank=True, null=True)),
                ('company_number_of_fulltime_employees', models.IntegerField(null=True)),
                ('company_number_of_paying_customers', models.IntegerField(null=True)),
                ('company_list_of_notable_customers', models.TextField(blank=True, null=True)),
                ('company_list_of_acquisitions', models.TextField(blank=True, null=True)),
                ('company_list_of_technology_integrations', models.TextField(blank=True, null=True)),
                ('company_hq_location_city', models.CharField(blank=True, max_length=150, null=True)),
                ('company_hq_location_state', models.CharField(blank=True, max_length=150, null=True)),
                ('company_hq_location_country', models.CharField(blank=True, max_length=150, null=True)),
                ('company_additional_notes', models.TextField(blank=True, null=True)),
                ('company_created_at', models.DateTimeField(auto_now_add=True)),
                ('company_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
