# Generated by Django 3.2.16 on 2022-10-24 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]
    atomic = False
    initial=True
    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compnay_id',
            new_name='company_id',
        ),
    ]
