# Generated by Django 3.2.16 on 2022-10-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_compnay_id_company_company_id'),
    ]
    atomic = False
    initial=True
    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_id',
            new_name='company_idd',
        ),
    ]
