# Generated by Django 3.2.16 on 2022-10-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_company_id_company_company_idd'),
    ]
    atomic = False
    initial=True
    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_idd',
            new_name='company_id',
        ),
    ]
